fix: docker build failed
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /opt/conda/envs/fyp-nlp-tm-production/lib/python3.9/site-packages/torch/lib/libtorch_python.so)